In [ ]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None #學生的分數
#scores_df:DataFrame | None = None #學生分數的DataFram

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,
                         columns=['國文', '英文', '數學', '地理', '歷史'],
                         index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名' , '性別']] = names_df [['姓名' , '性別']].head(n=50).values
scores_df = scores_df[['姓名' , '性別' ,'國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   楊志明  男  55  70  94  50  57
7    蕭博  男  80  47  77  69  73
8    馬芳  女  67  89  91  72  61
9   鄧雅婷  女  57  93  68  77  72
10   任廷  男  64  54  84  74  82

In [10]:
scores_df[scores_df['姓名'] =='鄧雅婷']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60")

     姓名 性別  國文  英文  數學  地理  歷史
9   鄧雅婷  女  57  93  68  77  72
11   馮敏  女  55  44  87  54  83
15  蔣嘉玲  女  55  56  78  96  47
24  余怡慈  女  56  63  96  80  73
38   丁穎  女  48  99  45  94  64
48   邱琳  女  59  95  84  85  47

In [12]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別  國文   英文   數學   地理  歷史   總分    平均    排名
26   葉琳  女  80   87   99   88  87  441  88.2   1.0
39   馮慧  女  73   96   93   75  92  429  85.8   2.0
20  馬建宏  男  70   80  100   55  99  404  80.8   3.0
16   呂瑾  女  98   93   40   86  85  402  80.4   4.0
44   馮超  男  84   83   53   96  81  397  79.4   5.0
28  呂冠霖  男  61   96   78   81  79  395  79.0   6.0
3   朱宗翰  男  80   70   84   83  66  383  76.6   7.0
50   馮軒  男  85   79   95   54  70  383  76.6   7.0
12   周傑  男  89   69   68   95  59  380  76.0   9.0
27   陳翔  男  62   99   89   70  60  380  76.0   9.0
8    馬芳  女  67   89   91   72  61  380  76.0   9.0
29   曹敏  女  86   65   57   84  87  379  75.8  12.0
1   余志偉  男  71   87   85   73  59  375  75.0  13.0
22  楊宗翰  男  40   91   64   95  83  373  74.6  14.0
14   黃霞  女  90   71   62   90  60  373  74.6  14.0
4    程恆  男  86   69   83   50  84  372  74.4  16.0
21   葉磊  男  62   85   56   69  99  371  74.2  17.0
48   邱琳  女  59   95   84   85  47  370  74.0  18.0
30   尹彥  男  73   83   40  100  74  370  74.0  18.0
24  余怡慈  女  56   63   96   80  73  368  73.6  20.0
9   鄧雅婷  女  57   93   68   77  72  367  73.4  21.0
5   馮志偉  男  40   66   88   93  78  365  73.0  22.0
37  何建國  男  58   98   53   66  87  362  72.4  23.0
10   任廷  男  64   54   84   74  82  358  71.6  24.0
33  許雅琪  女  83   56   53   90  76  358  71.6  24.0
46   何彥  男  67   92   76   81  42  358  71.6  24.0
34  胡子晴  女  99   89   41   73  54  356  71.2  27.0
38   丁穎  女  48   99   45   94  64  350  70.0  28.0
18   袁婷  女  65   74   62   53  94  348  69.6  29.0
23  唐宜蓁  女  95   44   75   40  93  347  69.4  30.0
42  陸柏翰  男  85   91   40   85  46  347  69.4  30.0
31  梁志明  男  73   76   60   86  52  347  69.4  30.0
7    蕭博  男  80   47   77   69  73  346  69.2  33.0
35  杜淑惠  女  96   78   45   64  53  336  67.2  34.0
13   黃超  男  70   62  100   55  45  332  66.4  35.0
15  蔣嘉玲  女  55   56   78   96  47  332  66.4  35.0
47   呂彥  男  55   66   94   59  57  331  66.2  37.0
41  曾俊傑  男  69   76   69   66  49  329  65.8  38.0
32   姜軍  男  65   51   92   68  50  326  65.2  39.0
6   楊志明  男  55   70   94   50  57  326  65.2  39.0
36  邱佳穎  女  87   44   40   77  78  326  65.2  39.0
19   蔡薇  女  98   84   44   57  41  324  64.8  42.0
45   唐瑜  女  72  100   40   71  40  323  64.6  43.0
11   馮敏  女  55   44   87   54  83  323  64.6  43.0
17  趙淑芬  女  79   59   54   76  45  313  62.6  45.0
2    丁娜  女  78   64   44   63  61  310  62.0  46.0
40   朱皓  男  49   63   75   57  61  305  61.0  47.0
43   余彥  男  53   99   51   52  44  299  59.8  48.0
25  宋子晴  女  68   56   51   52  60  287  57.4  49.0
49   鄭磊  男  72   66   53   45  46  282  56.4  50.0